### ISSUE TITLE
Need to adjust the html for drop down menu

### ISSUE THREAD

**Issue by hamzafastian** [hamzafastian/be92#4]
![buggy dropdown menu](https://user-images.githubusercontent.com/13987166/26887178-c19c882e-4bc0-11e7-8f90-36ca4f8fef0c.png)

Follow these steps below to see this dropdown menu
- Take latest pull of master.
- Run rake db:seed (It will create all dummy users)
**Admin**:
username: admin@be92.com
password: changeme

**Seller:**
username: seller@be92.com
password: changeme

**Buyer:**
username: buyer@be92.com
password: changeme

Now sign in to any of this account and you will see the `My Account` drop down in the header.

**Comment by RZeeshan** [comment]
hi hamza ,
I think we do not need to show these icons on drop down menu .

**Comment by hamzafastian** [comment]
Okay .please remove the icons and make them looks good with out icons
