### ISSUE TITLE
Pictures are not being displayed properly

### ISSUE THREAD

**Issue by mmehsan** [hamzafastian/be92#82]
Pictures are not being displayed properly on main page and item page

PFA
![2018-03-06_14-36-31](https://user-images.githubusercontent.com/31130683/37024877-f0479270-214b-11e8-855a-27851520299e.png)
![2018-03-06_14-36-53](https://user-images.githubusercontent.com/31130683/37024879-f08222e6-214b-11e8-97a5-ca1aaf661b42.png)

**Comment by hamzafastian** [comment]
Its the staging server path issue for old products. New uploading products will work fine
