### ISSUE TITLE
Variation quantity should always be less then total quantity

### ISSUE THREAD

**Issue by mmehsan** [hamzafastian/be92#91]
There should be some check that variation quantity should always be less then or equal to total quantity

PFA
![2018-03-06_15-31-18](https://user-images.githubusercontent.com/31130683/37027594-9f5b9caa-2153-11e8-8fbc-23b574439287.png)

**Comment by hamzafastian** [comment]
Try adding new products, it is already working, Old products might have this problem.
I will clear the database for staging for proper testing
