### ISSUE TITLE
Controls should be disabled during picture/video upload

### ISSUE THREAD

**Issue by mmehsan** [hamzafastian/be92#98]
Controls should be disabled during picture/video upload

PFA
![2018-03-06_17-40-07](https://user-images.githubusercontent.com/31130683/37032801-893bf6ec-2165-11e8-9e9e-8968005c3a34.jpg)

**Comment by hamzafastian** [comment]
Please try this with new store and products, it is working.

**Comment by hamzafastian** [comment]
Still working on it
